language: python
dist: xenial
sudo: false
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install virtualenv
script:
- make test
deploy:
  provider: script
  script:
    - pip install -U twine
    - twine upload . -r -u $PYPI_USERNAME -p $PYPI_PASSWORD
  on:
    #tags: true
    branch: hotfix/1.4.7
    python: '3.6'
    repo: vmalloc/Flask-Loopback
env:
  global:
    - secure: lEbSeRzRmrdmduGG4IpiS29ceV2DU0pwNsdl+riytAEqxMXywceCKdy4cdvsswnWcbSuLCEzam0kg0sxVLgFOIVxHy65fkuoiowHKLvnxc3eZBaYE8zprzP7JzmIhyHAedJj0W6Iqj+mkU1DMJYiIcGtGBsKPwNjlUfJo67GA38=
    - secure: ZNdeb9jIR5SzlWnnUEVwp+oJ5G1Nccj6Fs9M36HWoIEOYhxADGjdT3mOq/Kxoi6ZlBf5NnWkR8LUeFnmt9lqCjPlnJyfZuj7OEO49CkFAxZJb0Q9zOmXeDfEm9BmFPVqzhJJ8UacuMRh1Pv1hfVxjTXeIjYRiraH+1dOQtfnPOc=
